env:
  browser: true
  commonjs: true
  es2020: true
  jest: true
  node: true
extends:
  - 'eslint:recommended'
  - prettier
  - 'plugin:@typescript-eslint/recommended'
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
plugins:
  - prettier
  - '@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  project: true
  tsconfigRootDir: './'
  ecmaVersion: 11
rules:
  camelcase: 1
  no-underscore-dangle: 1
  no-param-reassign: 1
  global-require: 1
  prettier/prettier:
    - error
    - semi: false
    - printWidth: 120
  max-len:
    - 2
    - code: 120
  "require-await":
    - "error"
  "@typescript-eslint/no-floating-promises":
    - "error"
