

version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    image: sextant:${ISOLATION_ID}
  router:
    build:
      context: .
      dockerfile: Dockerfile.noxy
      args:
        EDITION_MODULE: dev.js
    image: noxy:${ISOLATION_ID} 
