version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.multistage
      args:
        EDITION_MODULE: dev.js
    image: sextant:${ISOLATION_ID}
  frontend-test:
    build:
      context: .
      dockerfile: Dockerfile.multistage
      args:
        EDITION_MODULE: dev.js
        NPM_TARGET: build-test
    image: sextant-ci:${ISOLATION_ID}
  frontend-enterprise:
    build:
      context: .
      dockerfile: Dockerfile.multistage
      args:
        EDITION_MODULE: enterprise.js
    image: sextant-enterprise:${ISOLATION_ID}
  frontend-standard:
    build:
      context: .
      dockerfile: Dockerfile.multistage
      args:
        EDITION_MODULE: standard.js
    image: sextant-standard:${ISOLATION_ID}
  frontend-premium:
    build:
      context: .
      dockerfile: Dockerfile.multistage
      args:
        EDITION_MODULE: premium.js
    image: sextant-premium:${ISOLATION_ID}
  frontend-sfs:
    build:
      context: .
      dockerfile: Dockerfile.multistage
      args:
        EDITION_MODULE: aws_sfs.js
    image: sextant-sfs:${ISOLATION_ID}
  frontend-sfd:
    build:
      context: .
      dockerfile: Dockerfile.multistage
      args:
        EDITION_MODULE: aws_sfd.js
    image: sextant-sfd:${ISOLATION_ID}
  frontend-sft:
    build:
      context: .
      dockerfile: Dockerfile.multistage
      args:
        EDITION_MODULE: sft.js
    image: sextant-sft:${ISOLATION_ID}
  router:
    build:
      context: .
      dockerfile: Dockerfile.noxy
    image: noxy:${ISOLATION_ID}
