#!/bin/bash

# set env variables from jenkins creds
docker-compose -f docker-compose.test.yaml up -d --build
sleep 2
docker-compose -f docker-compose.test.yaml exec -T frontend npm run test
exitcode=$?
docker-compose -f docker-compose.test.yaml stop
docker-compose -f docker-compose.test.yaml rm -f
exit $exitcode
